# Generated by Django 6.1.1 on 2026-10-08 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='المعرّف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الفكرة')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='المعرّف')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('max_members', models.PositiveSmallIntegerField(default=5, verbose_name='أقصى عدد لأعضاء الفريق')),
                ('status', models.CharField(choices=[('approved', 'معتمدة — متاحة للحجز'), ('booked', 'محجوزة'), ('closed', 'مغلقة')], db_index=True, default='approved', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ideas', to='ideas.category', verbose_name='التصنيف')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_ideas', to=settings.AUTH_USER_MODEL, verbose_name='المشرف')),
            ],
            options={
                'verbose_name': 'فكرة مشروع',
                'verbose_name_plural': 'أفكار المشاريع',
                'ordering': ['-created_at'],
            },
        ),
    ]
