# Generated by Django 6.1.1 on 2026-10-08 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='رسالة قصيرة للمشرف (اختياري)', verbose_name='ملاحظة من الطالب')),
                ('status', models.CharField(choices=[('pending', 'بانتظار موافقة المشرف'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحجز')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='ideas.projectidea', verbose_name='الفكرة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='الطالب الحائز')),
            ],
            options={
                'verbose_name': 'حجز فكرة',
                'verbose_name_plural': 'حجوزات الأفكار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('university_number', models.CharField(blank=True, max_length=30, verbose_name='الرقم الجامعي')),
                ('role', models.CharField(choices=[('leader', 'قائد الفريق'), ('member', 'عضو')], default='member', max_length=20, verbose_name='الدور داخل الفريق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='bookings.booking', verbose_name='الحجز')),
            ],
            options={
                'verbose_name': 'عضو فريق',
                'verbose_name_plural': 'أعضاء الفريق',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'approved'))), fields=('idea',), name='one_active_booking_per_idea'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'approved'))), fields=('student',), name='one_active_booking_per_student'),
        ),
    ]
